# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-10 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Student',
        ),
    ]
