# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190717_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(db_index=True, max_length=100)),
                ('brief_description', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='team',
            index_together=set([('id', 'slug')]),
        ),
    ]
